import React from 'react'
import './sample.css'
import sample from '../../../public/data/sample';
import SampleCard from './SampleCard';

const Samples = () => {
  return (
		<section className="contain sample">
			<h2 className="sample-title">Sample Books Generated by BookAI</h2>
			<p className="sample-content">
				Explore some of the captivating books created using our AI technology.
			</p>
      <div className="sample-data-container">
        {sample.map((data) => (
          <div className="sample-item" key={data.id}>
            <SampleCard data={data} key={data.id} />
          </div>
        ))}
      </div>
		</section>
	);
}

export default Samples