import { Inter } from "next/font/google";
import "./globals.css";
import { ModeProvider } from "@/context/ModeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "bookAI",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ModeProvider>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</ModeProvider>
	);
}
